services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  app:
    build: .
    depends_on:
      - mongodb
      - neo4j
      - qdrant
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017/
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      
  sync-neo4j:
    build: .
    command: python -m src.graph.sync_mongo_to_neo4j
    depends_on:
      - mongodb
      - neo4j
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017/
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      
  web-ui:
    build:
      context: ./src/web-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - neo4j
    environment:
      - REACT_APP_NEO4J_URI=bolt://neo4j:7687
      - REACT_APP_NEO4J_USER=neo4j
      - REACT_APP_NEO4J_PASSWORD=password
    volumes:
      - ./src/web-ui/src/config:/app/public/config

volumes:
  mongo_data:
  neo4j_data:
  qdrant_data: