[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "arxiv_pipeline"
version = "0.1.0"
description = "Local pipeline for processing ArXiv papers with graph and vector representation"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = [
    "requests>=2.28.0",
    "pymongo>=4.3.0",
    "neo4j>=5.5.0",
    "pyyaml>=6.0",
    "qdrant-client>=1.1.0",
    "sentence-transformers>=2.2.0",
    "pydantic>=2.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "mypy>=1.0.0",
]