# ArXiv Pipeline Configuration

# MongoDB settings
mongo:
  connection_string: "mongodb://mongodb:27017/"
  db_name: "arxiv_papers"
  
# Neo4j settings
neo4j:
  url: "bolt://neo4j:7687"
  user: "neo4j"
  password: "password"

# Qdrant settings
qdrant:
  url: "http://localhost:6333"
  collection_name: "arxiv_papers"
  vector_size: 768  # For sentence-transformers models

# ArXiv API settings
arxiv:
  categories:
    - "cs.AI"
    - "cs.CV"
    - "cs.CL"
    - "cs.DS"
    - "cs.GT" 
    - "cs.LG"  
    - "cs.LO"
    - "cs.MA"
    - "cs.NA"
    - "cs.NE"
    - "math.PR"
    - "physics.data-an"
    - "q-bio.NC"
    - "stat"
    - "stat.ML"
    - "stat.TH"
  max_results: 100
  sort_by: "submittedDate"
  sort_order: "descending"
  max_iterations: 2
  rate_limit_seconds: 3
  start_date: "2014-12-31"
  end_date: "2025-04-30"

# Embedding model settings
embedding:
  model_name: "all-MiniLM-L6-v2"  # Smaller model to start with
  batch_size: 32

# Logging settings
logging:
  level: "INFO"
  file: "logs/pipeline.log"